#!/bin/csh

if($# != 1) then
 echo "usage: $0 filename[.tex]"
 exit 1
endif

set a=$1

if($a:e == 'tex') then
 set a=$a:r
endif

if(! -f $a.tex) then
 echo $a.tex: No such file.
 exit 1
endif

nkf -e $a.tex | expand >! $a.euc.tex
< /dev/null platex $a.euc
if(! $?) then
   < /dev/null platex $a.euc && \mv $a.euc.dvi $a.dvi && dvipdfmx $a
endif

