#!/bin/sh

# usage: SFL2Verilog src.sfl dst.v [-h|--help]
#  src.sfl: name of source SFL file.
#  dst.v  : name of destination Verilog-HDL file.

parthenon_bindir=`parthenon_which -b`
parthenon_libexecdir=`parthenon_which -e`
parthenon_libdir=`parthenon_which -l`
parthenon_datadir=`parthenon_which -d`
img=${parthenon_libdir}/com/ver.img
pl="${parthenon_datadir}/com/verilog.pl ${parthenon_datadir}/com/trns.pl"

srcfile=''
dstfile=''
author='false'
help='false'
for arg in "$@"; do
 case ${arg} in
 -h | --help) help='true';;
 -a | --author) author='true';;
 *)
 if [ x"${srcfile}" = x ]; then
  srcfile="${a}"
 else
  if [ x"${dstfile}" = x ]; then
   dstfile="${a}"
  fi
 fi
 ;;
 esac
done

if [ x"${author}" = x"true" ]; then
 cat <<EOF

SFL2Verilog, an SFL->Verilog-HDL converter.
Designed and programmed on 1997/02/07 by Kiyoshi Oguri,
he is responsible for this program.

EOF
fi

if [ x"${help}" = x"true" ]; then
 cat <<EOF

usage: SFL2Verilog src.sfl dst.v [-h|--help]
 src.sfl: name of source SFL file.
 dst.v  : name of destination Verilog-HDL file.

EOF
exit 1
fi

${parthenon_libexecdir}/parthenon_banner -p SFL2Verilog
if [ -f ${img} ]; then
  ${parthenon_bindir}/prolog -i ${img} <<EOF
?-main('$1','$2',m_clock,posedge,p_reset,negedge,'1''b0',synopsys).
EOF
else
  ${parthenon_bindir}/prolog ${pl} <<EOF
?-image_save('ver.img'),main('$1','$2',m_clock,posedge,p_reset,negedge,'1''b0',synopsys).
EOF
fi
exit 0

